name = "MATH474"
uuid = "755902ed-ac2d-43b6-a89a-c3d45b7be12e"
authors = ["Mohammed Alshahrani <mmogib@gmail.com> and contributors"]
version = "1.1.1-DEV"

[deps]
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"

[compat]
RowEchelon = "0.2"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
